### ISSUE TITLE
Uncaught Error: Non-static method ConvertioCLI

### ISSUE THREAD

**Issue by cjmcqueen** [Convertio/convertio-cli#7]
Just got this message converting my first file (PDF to JPG) with the convertio CLI

```
DA> ~  convertio -f jpg /Users/../Downloads/8D29436916DF3C5682B1727CB688B0AD.pdf 
/Users/../Downloads/8D29436916DF3C5682B1727CB688B0AD.pdf: Done! => /Users/../8D29436916DF3C5682B1727CB688B0AD.pdf.jpg [248208 Bytes]

PHP Fatal error:  Uncaught Error: Non-static method ConvertioCLI\Info::printSystemMessage() cannot be called statically in phar:///usr/local/bin/convertio/src/Info.php:28
Stack trace:
#0 phar:///usr/local/bin/convertio/cli.php(91): ConvertioCLI\Info::printLine('\nAll Done!\n')
#1 /usr/local/bin/convertio(10): include('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/convertio/src/Info.php on line 28

Fatal error: Uncaught Error: Non-static method ConvertioCLI\Info::printSystemMessage() cannot be called statically in phar:///usr/local/bin/convertio/src/Info.php:28
Stack trace:
#0 phar:///usr/local/bin/convertio/cli.php(91): ConvertioCLI\Info::printLine('\nAll Done!\n')
#1 /usr/local/bin/convertio(10): include('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/convertio/src/Info.php on line 28

```

The file did convert and was placed in the folder specified.

**Comment by cjmcqueen** [comment]
It seems this error is thrown with any use of convertio

```
$> ~  convertio --help
PHP Fatal error:  Uncaught Error: Non-static method ConvertioCLI\Info::printSystemMessage() cannot be called statically in phar:///usr/local/bin/convertio/src/Info.php:34
Stack trace:
#0 phar:///usr/local/bin/convertio/cli.php(17): ConvertioCLI\Info::printHelp()
#1 /usr/local/bin/convertio(10): include('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/convertio/src/Info.php on line 34

Fatal error: Uncaught Error: Non-static method ConvertioCLI\Info::printSystemMessage() cannot be called statically in phar:///usr/local/bin/convertio/src/Info.php:34
Stack trace:
#0 phar:///usr/local/bin/convertio/cli.php(17): ConvertioCLI\Info::printHelp()
#1 /usr/local/bin/convertio(10): include('phar:///usr/loc...')
#2 {main}
  thrown in phar:///usr/local/bin/convertio/src/Info.php on line 34
```
